### PR TITLE
feat: rewired offer cats to have pagination and fixed few useeffect memory leaks

### PR DESCRIPTION
**Pull request by sunguru98**

### CODE REVIEW

**Comment by nazariyv** [comment]
Noticed this version you have worked on here: https://mooncat-git-fork-sunguru98-feature-offered-cats-p-000930.vercel.app/

Is missing the rarity (https://moncat.shop) like in prod below:
sss
 information like in prod

**Comment by nazariyv** [comment]
btw, since we are touching rarity here, would be worth downloading the fresh csv rarity file from here, converting it to json with some online converter and smacking it into the public folder. (they update that csv from time to time)

You can find that .csv here:

https://rarity.studio/cats.html

**Comment by sunguru98** [comment]
@nazariyv .. The fix has been made. It was due to an unnecessary ref logic check (which I forgot to remove after another technique implementation). Good catch BTW :) 
Screenshot_2021-03-25_at_6 56 24_AM

**Comment by nazariyv** [comment]
@sunguru98 insane work :) well done! can we incorporate that script of yours here to fetch the csv directly from rarity website, and fallback onto the pre-downloaded file we have in here.

And on top of that, let's add the data.json to git lfs. And then we are ready to merge this :)

**Comment by nazariyv** [comment]
oh yeah, almost forgot. For some reason, the cheapest cats section now shows 0 ETH cats. This is not correct. If the `to` address for the offer is not the zero address, i.e. 0x00...00, then that offer should not be shown. We show 0 ETH cats only and only if the to address is the zero address

**Comment by nazariyv** [comment]
closing, as this is now incorporated in the next.js migration here: https://github.com/re-nft/front-mooncat/pull/32

**Pull request closed without merging**
